added: translation attributes csv, documentation, tests
AdaptiveScale/rosetta pull request #153
Opened 2023-03-30 10:01 UTC by nbesimi

2023-04-06 09:12 UTC, ailegion requested changes
/lgtm - there only one comment about duplicates in gradle import

2023-04-06 09:12 UTC, ailegion commented on translator/build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.22'
duplicate

2023-04-06 14:33 UTC, jetroni commented on translator/src/main/java/com/adaptivescale/rosetta/translator/DefaultTranslator.java
> +        List<TranslationAttributeModel> translationAttributes = translationMatrix.findByTranslationAttributesByTranslationIds(translationModel.getId());
Can we call the singleton with getInstance method instead of storing it to prevent multi-thread issues?

2023-04-07 11:52 UTC, jetroni approved these changes

2023-04-07 11:58 UTC, merged